import { useState } from "react";
import { ChevronDown } from "lucide-react";

const faqData = [
  {
    question: "How do I create an account on CryptoMintX?",
    answer:
      "Getting started is simple. Click the Sign Up button and enter your username, email address, password, and an optional referral code if you were invited by another user. After completing registration, verify your email address to activate your account. Once your account is active, you can access your dashboard, manage deposits and withdrawals, track earnings, view referral statistics, and monitor your account level progression.",
  },
  {
    question: "What is the minimum deposit amount?",
    answer:
      "The minimum deposit required to activate your account and participate in available investment packages is 50 USDT. Deposits below this amount will not qualify for package benefits or daily yield calculations. After your deposit is confirmed on the blockchain and credited to your account, your selected package will become active and earnings will begin according to the package terms.",
  },
  {
    question: "What is the minimum withdrawal amount?",
    answer:
      "Users can submit withdrawal requests once their available balance reaches at least 50 USDT. This minimum threshold helps ensure efficient transaction processing and network fee management. Before submitting a withdrawal request, please verify that your wallet address is correct, as blockchain transactions cannot be reversed once processed.",
  },
  {
    question: "How long do withdrawals take?",
    answer:
      "Withdrawal requests are typically processed within 24 hours. Processing times may vary depending on blockchain network conditions, system maintenance, security reviews, or high transaction volumes. Once your withdrawal is approved and sent, you will receive a transaction record that can be used to track the transfer on the blockchain.",
  },
  {
    question: "How are daily returns calculated?",
    answer:
      "Daily returns are calculated based on your package tier and the amount of USDT deposited. Returns are calculated using the original principal amount and are not compounded automatically. For example, if you deposit 100 USDT in a package offering a 1% daily return, your daily earning would be 1 USDT. Earnings are credited according to the platform's reward schedule and can be monitored directly from your dashboard.",
  },
  {
    question: "What investment packages are available?",
    answer:
      "CryptoMintX offers multiple package tiers designed for different investment levels. The Starter package supports deposits from 50–200 USDT with a 1% daily return. The Pro package supports 201–1000 USDT with a 1.5% daily return. The Master package covers 1001–2000 USDT with a 2.5% daily return. The Elite package supports 2001–4500 USDT with a 3% daily return, while the Empire package covers 4501–10000 USDT with a 3.3% daily return.",
  },
  {
    question: "How does the referral bonus work?",
    answer:
      "Our referral system rewards users for growing the community. When a new user registers using your referral code and successfully makes a qualifying deposit, you receive a one-time referral bonus equal to 5% of their deposit amount. For example, if your referral deposits 1,000 USDT, you will receive a 50 USDT referral reward. Referral rewards are credited directly to your account and can be viewed in your referral history.",
  },
  {
    question: "What are Level A, Level B, and Level C team members?",
    answer:
      "The team structure is built around three referral levels. Users you directly invite become your Level A team members. If a Level A member invites someone, that person becomes your Level B team member. Likewise, users invited by your Level B members become your Level C team members. This structure allows users to build a larger network and qualify for additional team commissions and level upgrades based on overall team growth.",
  },
  {
    question: "How do I upgrade my user level?",
    answer:
      "User levels are upgraded automatically when specific team growth requirements are met. Each level requires a combination of Level A, Level B, and Level C team members. For example, advancing from Level 1 to Level 2 requires a total of 8 qualified team members, including 3 Level A members and 5 Level B/C members. Higher levels unlock increased commission percentages and additional earning opportunities within the team structure.",
  },
  {
    question: "How are team commissions calculated?",
    answer:
      "Team commissions are calculated based on your current user level and the earnings generated by your Level A, Level B, and Level C team members. As your account level increases, your commission percentages also increase. For example, a Level 2 user can earn 12% from Level A earnings, 5% from Level B earnings, and 2% from Level C earnings. The system automatically tracks team performance, calculates commissions, and updates your earnings history, allowing you to monitor all team-generated rewards directly from your dashboard.",
  },
];

export default function HelpCenter() {
  const [active, setActive] = useState(null);

  const toggleFAQ = (index) => {
    setActive(active === index ? null : index);
  };

  return (
    <section className="bg-black py-20 px-4 lg:px-8">
      <div className="mx-auto max-w-6xl">

        {/* Heading */}
        <h2
          className="
          text-center
          text-4xl
          lg:text-6xl
          font-bold
          text-white
          drop-shadow-[0_0_20px_rgba(255,255,255,.8)]
          "
        >
          Frequently Asked Questions
        </h2>

        {/* FAQ */}
        <div className="mt-16 space-y-4">

          {faqData.map((item, index) => (
            <div
              key={index}
              className="
              border-b
              border-zinc-800
              pb-4
              "
            >
              <button
                onClick={() => toggleFAQ(index)}
                className="
                w-full
                flex
                items-center
                justify-between
                gap-4
                text-left
                py-4
                "
              >
                <div className="flex gap-5">
                  <span
                    className="
                    min-w-[20px]
                    text-white
                    font-semibold
                    "
                  >
                    {index + 1}
                  </span>

                  <span
                    className="
                    text-white
                    text-lg
                    lg:text-2xl
                    "
                  >
                    {item.question}
                  </span>
                </div>

                <ChevronDown
                  className={`
                    transition-transform duration-300
                    ${
                      active === index
                        ? "rotate-180"
                        : ""
                    }
                  `}
                />
              </button>

              <div
                className={`
                  overflow-hidden
                  transition-all
                  duration-300
                  ${
                    active === index
                      ? "max-h-40 opacity-100"
                      : "max-h-0 opacity-0"
                  }
                `}
              >
                <p
                  className="
                  pl-9
                  pb-4
                  text-zinc-400
                  "
                >
                  {item.answer}
                </p>
              </div>

            </div>
          ))}

        </div>

        {/* CTA */}
        <div className="mt-16 flex justify-center">

          <button
            className="
            rounded-full
            bg-[#1D66FF]
            px-10
            py-4
            text-lg
            font-medium
            text-white
            transition
            hover:bg-blue-700
            "
          >
            Sign Up Now
          </button>

        </div>

      </div>
    </section>
  );
}